"""A collection's tables are identical in shape to the global ones — §6.3.

The design does not say "similar": it says the ORM classes for a collection
are generated by the *same factory* that builds the global ones, so the
SQLModel, soft-delete and audit behaviour is identical by construction. This
file is what makes that claim falsifiable — it compiles the DDL of both sets
and compares them with the prefix substituted away.

What the comparison deliberately does **not** normalise is as important as
what it does. Column names, types, nullability, defaults, the primary key, the
foreign key's target and ``ON DELETE``, every index's name, its column list,
its uniqueness and its ``WHERE`` predicate all have to match exactly once the
prefix is rewritten. The one thing elided is the *generated name* of a foreign
key constraint, because the framework's naming convention truncates it with a
hash once the table name grows — ``fk_records_c_events_index_text_record_id_…``
is over Postgres's 63-byte identifier limit and the convention shortens it.
That is a property of the convention, not of this module, and the FK's shape
is still compared.
"""

from __future__ import annotations

import re

import pytest
from sm_records.models import Base, table_set
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from tests.collections_harness import COLLECTION_NAMES

SUFFIXES = (
    "record",
    "revision",
    "index_text",
    "index_number",
    "index_bool",
    "index_date",
    "index_datetime",
    "index_ref",
)
"""Every table a table set owns. The reduce table is **not** one of them: it is
keyed by ``type_id`` with no ``record_id`` to partition on, so it stays global
for every collection (§6.4), and its absence here is the assertion."""

_DIALECT = postgresql.dialect()
_FK_NAME = re.compile(r"CONSTRAINT \S+ FOREIGN KEY")


def _ddl(prefix: str) -> str:
    out: list[str] = []
    for suffix in SUFFIXES:
        table = Base.metadata.tables[f"{prefix}{suffix}"]
        out.append(str(CreateTable(table).compile(dialect=_DIALECT)).strip())
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            out.append(str(CreateIndex(index).compile(dialect=_DIALECT)).strip())
    return "\n".join(out)


@pytest.mark.parametrize("name", COLLECTION_NAMES)
def test_a_collections_ddl_equals_the_global_ddl_modulo_the_prefix(name):
    theirs = _ddl(f"records_c_{name}_").replace(f"records_c_{name}_", "records_")
    ours = _ddl("records_")
    # The status/revision enum types are named after the prefix too, so the
    # substitution above already realigns them; only the FK constraint name is
    # hash-truncated and cannot be rewritten. See the module docstring.
    assert _FK_NAME.sub("CONSTRAINT <fk> FOREIGN KEY", theirs) == _FK_NAME.sub(
        "CONSTRAINT <fk> FOREIGN KEY", ours
    )


@pytest.mark.parametrize("name", COLLECTION_NAMES)
def test_every_index_name_is_the_global_one_with_the_prefix_substituted(name):
    """Index names are schema-global on Postgres, so a collection's copies
    cannot reuse them — and must not invent a different scheme either, or the
    DDL comparison above would be comparing two things nobody can map onto
    each other by hand."""
    for suffix in SUFFIXES:
        theirs = Base.metadata.tables[f"records_c_{name}_{suffix}"]
        ours = Base.metadata.tables[f"records_{suffix}"]
        renamed = {
            (index.name or "").replace(f"records_c_{name}_", "records_") for index in theirs.indexes
        }
        assert renamed == {index.name for index in ours.indexes}


@pytest.mark.parametrize("name", COLLECTION_NAMES)
def test_the_slug_index_keeps_its_partial_predicate(name):
    """Alembic does not compare an index's ``WHERE``, so nothing downstream
    would report this missing — a collection whose slug index covered trashed
    *and* live rows without the predicate would silently allow two records to
    claim one slug."""
    table = Base.metadata.tables[f"records_c_{name}_record"]
    slug = next(i for i in table.indexes if i.name == f"ix_records_c_{name}_record_type_slug")
    assert slug.unique
    assert [c.name for c in slug.columns] == ["type_id", "locale", "slug"]
    rendered = str(CreateIndex(slug).compile(dialect=_DIALECT))
    assert "WHERE slug IS NOT NULL" in rendered


def test_the_reduce_table_is_global_and_has_no_per_collection_copy():
    """§6.4. A reduce row is a fold over many records keyed by ``type_id``;
    there is no ``record_id`` to partition on, so a collection gains nothing
    from its own copy and would gain one more table to rebuild."""
    assert "records_index_reduce" in Base.metadata.tables
    for name in COLLECTION_NAMES:
        assert f"records_c_{name}_index_reduce" not in Base.metadata.tables


@pytest.mark.parametrize("name", COLLECTION_NAMES)
def test_a_collections_index_rows_point_at_its_own_record_table(name):
    """The foreign key is the half the name substitution above cannot check on
    its own: a collection whose index tables cascaded from ``records_record``
    would delete the wrong rows on a purge."""
    tables = table_set(name)
    for index_table in tables.index_tables:
        targets = {fk.column.table.name for fk in index_table.__table__.foreign_keys}
        assert targets == {f"records_c_{name}_record"}
    revision_targets = {fk.column.table.name for fk in tables.revision.__table__.foreign_keys}
    assert revision_targets == {f"records_c_{name}_record"}
    # ...and the document table still points at the **global** type table,
    # because ``records_type`` is what names the collection (§6.4).
    record_targets = {fk.column.table.name for fk in tables.record.__table__.foreign_keys}
    assert record_targets == {"records_type"}
