"""add page trash

Revision ID: 0cce3a443a27
Revises: af06f6ea093e
Create Date: 2026-08-19 15:46:03.220566
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0cce3a443a27'
down_revision: str | None = 'af06f6ea093e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagebuilder_pages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_pagebuilder_pages_deleted_at'), 'pagebuilder_pages', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagebuilder_pages_deleted_at'), table_name='pagebuilder_pages')
    op.drop_column('pagebuilder_pages', 'deleted_at')
    # ### end Alembic commands ###
