"""records reduce index: maintained aggregates keyed by (type, key, group)

Revision ID: 26bfe5e5f063
Revises: a7c3e1d4b920
Create Date: 2026-09-20 10:38:54.640462

Autogenerated and left as generated — the table is additive, empty on arrival
and has no data to backfill, which is what the ``a7c3e1d4b920`` revision above
it could not say about itself.

Three things about the shape are deliberate and would look like omissions:

* **No foreign key to ``records_record``.** Every other ``records_index_*``
  row is a projection of one record and cascades from it; a row here is a
  *fold* over many, so there is no record to cascade from. The writer keeps it
  by delta and a type delete removes its rows explicitly
  (``services._lifecycle.purge_type_records``).
* **``sum`` is nullable.** A reduce spec that declares no ``value`` stores
  ``NULL`` there, which is not the same fact as ``0`` — a fold of values that
  cancel.
* **The unique index is the constraint that matters.** ``(type_id, key,
  group_value)`` is what makes the incremental ``UPDATE … SET count = count +
  :d`` address exactly one row, and what turns two writers racing to create
  the same group into an ``IntegrityError`` one of them retries rather than
  into two rows that each hold half the count.

Downgrading is clean: the table is derivable from the records in full
(``python -m sm_records.cli reindex`` rebuilds it), so dropping it loses
nothing that cannot be recomputed.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26bfe5e5f063"
down_revision: str | None = "a7c3e1d4b920"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "records_index_reduce",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("group_value", sa.String(length=512), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("sum", sa.Numeric(precision=19, scale=5), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_records_index_reduce")),
    )
    op.create_index(
        "ix_records_index_reduce_lookup", "records_index_reduce", ["type_id", "key"], unique=False
    )
    op.create_index(
        "uq_records_index_reduce_group",
        "records_index_reduce",
        ["type_id", "key", "group_value"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_records_index_reduce_group", table_name="records_index_reduce")
    op.drop_index("ix_records_index_reduce_lookup", table_name="records_index_reduce")
    op.drop_table("records_index_reduce")
    # ### end Alembic commands ###
