"""records events collection tables: the demo host's one collection

Revision ID: 3b4733cf5444
Revises: 5e2a32dccc22
Create Date: 2026-09-20 11:26:31.600166

Autogenerated and left as generated. These eight tables exist because
``host/records_collections.py`` calls ``declare_collection("events")``
(Phase 5 §6.1) — one document table, one revision log and the six index
tables, identical in shape to ``records_record`` / ``records_revision`` /
``records_index_*`` with the prefix ``records_c_events_``, because they are
built by the same factories (``sm_records.models._record`` and
``sm_records.models._index``).

**A host that declares no collection can skip this revision.** It is a separate
revision from ``5e2a32dccc22`` for exactly that reason: that one adds the
nullable ``records_type.collection`` column and is what every host needs; this
one creates tables that only a host running *this* declaration will ever write
a row into. Skipping it means stamping past it, since Alembic history is
linear here (CLAUDE.md) — or, on a host starting fresh, simply not having this
file, because each consuming host autogenerates its own revision against its
own declarations.

Two shapes are the collection's and not the global set's, and would look like
mistakes:

* **Every index and the status enum are named after this table**, not after
  ``records_record``. Index names and Postgres enum type names are
  schema-global, so ``ix_records_record_type_slug`` and
  ``records_record_status`` can exist exactly once — the factories derive both
  from the prefix for that reason.
* **The partial unique slug index keeps its ``WHERE slug IS NOT NULL``.**
  Alembic does not compare an index predicate, so a hand-edit that dropped it
  here would never be reported; the rule in ``models/_record_args.py`` applies
  to this copy word for word.

There is **no** ``records_c_events_index_reduce``. A reduce row is a fold keyed
by ``type_id`` with no record to cascade from, so the reduce table stays global
for every collection (§6.4).

Downgrading drops all eight. That destroys the records in this collection, so
it is only safe once the types naming it are gone — which is also what makes
dropping ``records_type.collection`` beneath it safe.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3b4733cf5444'
down_revision: str | None = '5e2a32dccc22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records_c_events_record',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='records_c_events_record_status'), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('translation_group', sa.String(length=32), nullable=False),
    sa.Column('display_title', sa.String(length=300), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['records_type.id'], name=op.f('fk_records_c_events_record_type_id_records_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_c_events_record'))
    )
    op.create_index('ix_records_c_events_record_group_locale', 'records_c_events_record', ['translation_group', 'locale'], unique=True)
    op.create_index(op.f('ix_records_c_events_record_published_at'), 'records_c_events_record', ['published_at'], unique=False)
    op.create_index(op.f('ix_records_c_events_record_status'), 'records_c_events_record', ['status'], unique=False)
    op.create_index(op.f('ix_records_c_events_record_translation_group'), 'records_c_events_record', ['translation_group'], unique=False)
    op.create_index('ix_records_c_events_record_type_created_id', 'records_c_events_record', ['type_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_records_c_events_record_type_id'), 'records_c_events_record', ['type_id'], unique=False)
    op.create_index('ix_records_c_events_record_type_position_id', 'records_c_events_record', ['type_id', 'position', 'id'], unique=False)
    op.create_index('ix_records_c_events_record_type_published_id', 'records_c_events_record', ['type_id', 'published_at', 'id'], unique=False)
    op.create_index('ix_records_c_events_record_type_slug', 'records_c_events_record', ['type_id', 'locale', 'slug'], unique=True, postgresql_where=sa.text('slug IS NOT NULL'), sqlite_where=sa.text('slug IS NOT NULL'))
    op.create_index('ix_records_c_events_record_type_slug_id', 'records_c_events_record', ['type_id', 'slug', 'id'], unique=False)
    op.create_index('ix_records_c_events_record_type_status_position', 'records_c_events_record', ['type_id', 'status', 'position'], unique=False)
    op.create_index('ix_records_c_events_record_type_title_id', 'records_c_events_record', ['type_id', 'display_title', 'id'], unique=False)
    op.create_index('ix_records_c_events_record_type_updated_id', 'records_c_events_record', ['type_id', 'updated_at', 'id'], unique=False)
    op.create_index(op.f('ix_records_c_events_record_uuid'), 'records_c_events_record', ['uuid'], unique=True)
    op.create_table('records_c_events_index_bool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records_c_events_record.id'], name=op.f('fk_records_c_events_index_bool_record_id_records_c_events_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_c_events_index_bool'))
    )
    op.create_index('ix_records_c_events_index_bool_lookup', 'records_c_events_index_bool', ['type_id', 'field_key', 'value'], unique=False)
    op.create_index('ix_records_c_events_index_bool_record', 'records_c_events_index_bool', ['record_id'], unique=False)
    op.create_table('records_c_events_index_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records_c_events_record.id'], name=op.f('fk_records_c_events_index_date_record_id_records_c_events_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_c_events_index_date'))
    )
    op.create_index('ix_records_c_events_index_date_lookup', 'records_c_events_index_date', ['type_id', 'field_key', 'value'], unique=False)
    op.create_index('ix_records_c_events_index_date_record', 'records_c_events_index_date', ['record_id'], unique=False)
    op.create_table('records_c_events_index_datetime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records_c_events_record.id'], name=op.f('fk_records_c_events_index_datetime_record_id_records_c_events_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_c_events_index_datetime'))
    )
    op.create_index('ix_records_c_events_index_datetime_lookup', 'records_c_events_index_datetime', ['type_id', 'field_key', 'value'], unique=False)
    op.create_index('ix_records_c_events_index_datetime_record', 'records_c_events_index_datetime', ['record_id'], unique=False)
    op.create_table('records_c_events_index_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=19, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records_c_events_record.id'], name=op.f('fk_records_c_events_index_number_record_id_records_c_events_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_c_events_index_number'))
    )
    op.create_index('ix_records_c_events_index_number_lookup', 'records_c_events_index_number', ['type_id', 'field_key', 'value'], unique=False)
    op.create_index('ix_records_c_events_index_number_record', 'records_c_events_index_number', ['record_id'], unique=False)
    op.create_table('records_c_events_index_ref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('target_uuid', sa.String(length=32), nullable=False),
    sa.Column('target_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records_c_events_record.id'], name=op.f('fk_records_c_events_index_ref_record_id_records_c_events_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_c_events_index_ref'))
    )
    op.create_index('ix_records_c_events_index_ref_lookup', 'records_c_events_index_ref', ['type_id', 'field_key', 'target_uuid'], unique=False)
    op.create_index('ix_records_c_events_index_ref_record', 'records_c_events_index_ref', ['record_id'], unique=False)
    op.create_index('ix_records_c_events_index_ref_target', 'records_c_events_index_ref', ['target_uuid'], unique=False)
    op.create_table('records_c_events_index_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('value_full', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records_c_events_record.id'], name=op.f('fk_records_c_events_index_text_record_id_records_c_events_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_c_events_index_text'))
    )
    op.create_index('ix_records_c_events_index_text_lookup', 'records_c_events_index_text', ['type_id', 'field_key', 'value'], unique=False)
    op.create_index('ix_records_c_events_index_text_record', 'records_c_events_index_text', ['record_id'], unique=False)
    op.create_table('records_c_events_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('display_title', sa.String(length=300), nullable=False),
    sa.Column('event', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'RESTORE', name='records_c_events_revision_event'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records_c_events_record.id'], name=op.f('fk_records_c_events_revision_record_id_records_c_events_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_c_events_revision'))
    )
    op.create_index('ix_records_c_events_revision_record_id', 'records_c_events_revision', ['record_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_records_c_events_revision_record_id', table_name='records_c_events_revision')
    op.drop_table('records_c_events_revision')
    op.drop_index('ix_records_c_events_index_text_record', table_name='records_c_events_index_text')
    op.drop_index('ix_records_c_events_index_text_lookup', table_name='records_c_events_index_text')
    op.drop_table('records_c_events_index_text')
    op.drop_index('ix_records_c_events_index_ref_target', table_name='records_c_events_index_ref')
    op.drop_index('ix_records_c_events_index_ref_record', table_name='records_c_events_index_ref')
    op.drop_index('ix_records_c_events_index_ref_lookup', table_name='records_c_events_index_ref')
    op.drop_table('records_c_events_index_ref')
    op.drop_index('ix_records_c_events_index_number_record', table_name='records_c_events_index_number')
    op.drop_index('ix_records_c_events_index_number_lookup', table_name='records_c_events_index_number')
    op.drop_table('records_c_events_index_number')
    op.drop_index('ix_records_c_events_index_datetime_record', table_name='records_c_events_index_datetime')
    op.drop_index('ix_records_c_events_index_datetime_lookup', table_name='records_c_events_index_datetime')
    op.drop_table('records_c_events_index_datetime')
    op.drop_index('ix_records_c_events_index_date_record', table_name='records_c_events_index_date')
    op.drop_index('ix_records_c_events_index_date_lookup', table_name='records_c_events_index_date')
    op.drop_table('records_c_events_index_date')
    op.drop_index('ix_records_c_events_index_bool_record', table_name='records_c_events_index_bool')
    op.drop_index('ix_records_c_events_index_bool_lookup', table_name='records_c_events_index_bool')
    op.drop_table('records_c_events_index_bool')
    op.drop_index(op.f('ix_records_c_events_record_uuid'), table_name='records_c_events_record')
    op.drop_index('ix_records_c_events_record_type_updated_id', table_name='records_c_events_record')
    op.drop_index('ix_records_c_events_record_type_title_id', table_name='records_c_events_record')
    op.drop_index('ix_records_c_events_record_type_status_position', table_name='records_c_events_record')
    op.drop_index('ix_records_c_events_record_type_slug_id', table_name='records_c_events_record')
    op.drop_index('ix_records_c_events_record_type_slug', table_name='records_c_events_record', postgresql_where=sa.text('slug IS NOT NULL'), sqlite_where=sa.text('slug IS NOT NULL'))
    op.drop_index('ix_records_c_events_record_type_published_id', table_name='records_c_events_record')
    op.drop_index('ix_records_c_events_record_type_position_id', table_name='records_c_events_record')
    op.drop_index(op.f('ix_records_c_events_record_type_id'), table_name='records_c_events_record')
    op.drop_index('ix_records_c_events_record_type_created_id', table_name='records_c_events_record')
    op.drop_index(op.f('ix_records_c_events_record_translation_group'), table_name='records_c_events_record')
    op.drop_index(op.f('ix_records_c_events_record_status'), table_name='records_c_events_record')
    op.drop_index(op.f('ix_records_c_events_record_published_at'), table_name='records_c_events_record')
    op.drop_index('ix_records_c_events_record_group_locale', table_name='records_c_events_record')
    op.drop_table('records_c_events_record')
    # ### end Alembic commands ###
