"""add pagebuilder

Revision ID: 4cf1b4c9f8f9
Revises: ed06f4584f6b
Create Date: 2026-08-03 16:11:15.989228
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4cf1b4c9f8f9'
down_revision: str | None = 'ed06f4584f6b'
# Marks the start of pagebuilder's history so the module can be downgraded on
# its own: `alembic downgrade pagebuilder@base`.
branch_labels: str | Sequence[str] | None = ("pagebuilder",)
depends_on: str | Sequence[str] | None = None


def _drop_enums(*names: str) -> None:
    """Drop the Postgres enum types the dropped tables owned.

    ``op.drop_table`` builds a bare ``Table`` with no type metadata, so on
    Postgres ``DROP TABLE`` leaves the ``CREATE TYPE`` behind and the next
    ``upgrade`` past this revision fails with
    ``DuplicateObject: type "%s" already exists``. Every other dialect here is
    SQLite, which has no such object: ``Enum.drop`` is a no-op on a dialect
    without native enums, and the guard says so rather than relying on it.

    Same helper as ``e23090832709``'s, which added it for ``records``. It is
    copied rather than imported because a revision file has to keep working
    when the ones around it are squashed away.
    """
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    for name in names:
        sa.Enum(name=name).drop(bind, checkfirst=True)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagebuilder_layout',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_data', sa.JSON(), nullable=False),
    sa.Column('footer_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagebuilder_layout'))
    )
    op.create_table('pagebuilder_media',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('folder', sa.String(length=300), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagebuilder_media'))
    )
    op.create_index(op.f('ix_pagebuilder_media_filename'), 'pagebuilder_media', ['filename'], unique=True)
    op.create_index(op.f('ix_pagebuilder_media_folder'), 'pagebuilder_media', ['folder'], unique=False)
    op.create_table('pagebuilder_pages',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('og_image', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED_FOR_REVIEW', 'PUBLISHED', name='pagebuilder_page_status'), nullable=False),
    sa.Column('draft_data', sa.JSON(), nullable=False),
    sa.Column('published_data', sa.JSON(), nullable=True),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('index_in_search', sa.Boolean(), nullable=False),
    sa.Column('json_ld', sa.JSON(), nullable=True),
    sa.Column('rejection_note', sa.String(length=2000), nullable=True),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unpublish_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagebuilder_pages'))
    )
    op.create_index(op.f('ix_pagebuilder_pages_slug'), 'pagebuilder_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_pagebuilder_pages_status'), 'pagebuilder_pages', ['status'], unique=False)
    op.create_table('pagebuilder_layout_revisions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('header_data', sa.JSON(), nullable=False),
    sa.Column('footer_data', sa.JSON(), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['layout_id'], ['pagebuilder_layout.id'], name=op.f('fk_pagebuilder_layout_revisions_layout_id_pagebuilder_layout')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagebuilder_layout_revisions'))
    )
    op.create_index(op.f('ix_pagebuilder_layout_revisions_layout_id'), 'pagebuilder_layout_revisions', ['layout_id'], unique=False)
    op.create_table('pagebuilder_page_revisions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('og_image', sa.String(length=500), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('event', sa.Enum('PUBLISH', 'UNPUBLISH', 'SUBMIT', 'APPROVE', 'REJECT', name='pagebuilder_revision_event'), server_default='PUBLISH', nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pagebuilder_pages.id'], name=op.f('fk_pagebuilder_page_revisions_page_id_pagebuilder_pages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagebuilder_page_revisions'))
    )
    op.create_index(op.f('ix_pagebuilder_page_revisions_event'), 'pagebuilder_page_revisions', ['event'], unique=False)
    op.create_index(op.f('ix_pagebuilder_page_revisions_page_id'), 'pagebuilder_page_revisions', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagebuilder_page_revisions_page_id'), table_name='pagebuilder_page_revisions')
    op.drop_index(op.f('ix_pagebuilder_page_revisions_event'), table_name='pagebuilder_page_revisions')
    op.drop_table('pagebuilder_page_revisions')
    op.drop_index(op.f('ix_pagebuilder_layout_revisions_layout_id'), table_name='pagebuilder_layout_revisions')
    op.drop_table('pagebuilder_layout_revisions')
    op.drop_index(op.f('ix_pagebuilder_pages_status'), table_name='pagebuilder_pages')
    op.drop_index(op.f('ix_pagebuilder_pages_slug'), table_name='pagebuilder_pages')
    op.drop_table('pagebuilder_pages')
    op.drop_index(op.f('ix_pagebuilder_media_folder'), table_name='pagebuilder_media')
    op.drop_index(op.f('ix_pagebuilder_media_filename'), table_name='pagebuilder_media')
    op.drop_table('pagebuilder_media')
    op.drop_table('pagebuilder_layout')
    # ### end Alembic commands ###
    _drop_enums("pagebuilder_page_status", "pagebuilder_revision_event")
