"""records: tenant_id on the tenant-owned tables

Revision ID: 4ecb931245dd
Revises: 8f3d223f8605
Create Date: 2026-09-23 13:00:00.000000

Records adopts the framework's ``MultiTenantMixin``
(``modules/records/docs`` and ``docs/plans/2026-09-23-records-multitenancy.md``
§B–§D). Six kinds of table get ``tenant_id VARCHAR(50) NOT NULL`` plus the
mixin's ``ix_<table>_tenant_id``: ``records_type``, ``records_type_revision``,
and each present table set's ``<set>_record`` and ``<set>_revision``. The index
and reduce tables do not: their rows are derived, written in bulk and reached
through ``type_id``/``record_id``.

* **Backfill** with a constant ``server_default='default'`` — on Postgres ≥ 11 a
  catalog-only fast default, no table rewrite (1.1 ms on 200k rows) — and **the
  default is dropped in this same revision**, so a statement that forgets the
  tenant is a ``NOT NULL`` failure again rather than a row silently filed under
  ``default``. It also keeps the migrated schema equal to a ``create_all`` one.
* **Per-tenant natural keys.** ``ix_records_type_key UNIQUE (key)`` becomes
  ``uq_records_type_tenant_key UNIQUE (tenant_id, key)``, and each set's
  ``ix_<set>_record_uuid UNIQUE (uuid)`` becomes ``uq_<set>_record_tenant_uuid
  UNIQUE (tenant_id, uuid)``. The slug and translation-group uniques are left
  alone: they lead with ``type_id``, which now implies the tenant.
* **A record's tenant is its type's.** ``records_type`` gains
  ``uq_records_type_id_tenant_id UNIQUE (id, tenant_id)``, and each set's
  ``fk_<set>_record_type_id_records_type`` becomes ``(type_id, tenant_id) ->
  records_type (id, tenant_id) ON DELETE RESTRICT`` under the same name. The name
  is read off the model's constraint rather than spelled, so a collection name
  long enough for the convention to hash-truncate it is dropped by the spelling
  the database actually holds (``models/_index.py``).

``DEFAULT`` repeats ``sm_records.tenancy.DEFAULT_TENANT`` on purpose: a revision
must not change meaning if the constant ever moves.

**Which table sets** comes from the database, by the rule ``fe3ea2dfe0fb`` sets
out (:func:`_present_sets`): a collection declared after this revision gets the
columns from its own autogenerated creation revision.

**SQLite** cannot alter a constraint or drop a column default in place, so those
steps go through ``batch_alter_table(recreate="always")`` — which recreates the
three ``…_desc`` indexes *ascending* (their ``DESC`` is lost in reflection), so
they are re-issued from the model afterwards, as ``c4a17b9de0f2`` created them.
Then ``ANALYZE``, for the reason ``c4a17b9de0f2`` gives: an unanalysed index is
assumed selective, and every records statement now filters on ``tenant_id``.
The batch branch cannot run offline (``--sql``), like every earlier SQLite batch
revision; the Postgres branch is plain DDL.

**Large tables (Postgres).** The two unique indexes block writes while they
build (~0.5 s per 200k records) and the new foreign key validates every row
(~60 ms per 200k). Above about a million records run them as ``CREATE UNIQUE
INDEX CONCURRENTLY`` in a separate non-transactional revision and add the key
``NOT VALID`` + ``VALIDATE CONSTRAINT`` — ``docs/operations.md``.

**Downgrading is lossy, and refusable.** It restores the global uniques, so it
is refused outright once two tenants share a type key or a record uuid — checked
up front, before any DDL, because SQLite's DDL is not transactional and a unique
failing half way would strand the schema between revisions — and where it
succeeds it merges every tenant's rows into one install with no way to tell them
apart again. Only a single-tenant database — every row ``default`` — round-trips.
"""

from collections.abc import Iterator, Sequence

import sqlalchemy as sa
from alembic import op
from sm_records.models import TableSet, table_sets
from sm_records.models._record_args import descending_index_names

# revision identifiers, used by Alembic.
revision: str = "4ecb931245dd"
down_revision: str | None = "8f3d223f8605"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

DEFAULT = "default"
COLUMN = "tenant_id"
TYPE_TABLE = "records_type"
TYPE_ID_TENANT = "uq_records_type_id_tenant_id"


def _present_sets() -> tuple[TableSet, ...]:
    """The declared table sets whose document table exists in this database —
    ``fe3ea2dfe0fb._present_sets``, for the reason given there. Offline, every
    declared set."""
    if op.get_context().as_sql:
        return table_sets()
    present = set(sa.inspect(op.get_bind()).get_table_names())
    return tuple(tables for tables in table_sets() if tables.record.__tablename__ in present)


def _owned(sets: Sequence[TableSet]) -> list[str]:
    out = [TYPE_TABLE, "records_type_revision"]
    for tables in sets:
        out += [tables.record.__tablename__, tables.revision.__tablename__]
    return out


def _fk_name(tables: TableSet) -> str:
    """The type key's name as the model builds it — see the module docstring."""
    table = tables.record.__table__
    found = next(c for c in table.foreign_key_constraints if "type_id" in c.column_keys)
    return found.name


def _column(**kw) -> sa.Column:
    return sa.Column(COLUMN, sa.String(50), nullable=False, **kw)


def _swap_natural_keys(sets: Sequence[TableSet], *, tenant: bool) -> None:
    """Global uniques -> per-tenant uniques (``tenant=True``), or back."""
    old, new = ("ix_records_type_key", ["key"]), ("uq_records_type_tenant_key", [COLUMN, "key"])
    drop, create = (old, new) if tenant else (new, old)
    op.drop_index(drop[0], table_name=TYPE_TABLE)
    op.create_index(create[0], TYPE_TABLE, create[1], unique=True)
    for tables in sets:
        rec = tables.record.__tablename__
        old, new = (f"ix_{rec}_uuid", ["uuid"]), (f"uq_{rec}_tenant_uuid", [COLUMN, "uuid"])
        drop, create = (old, new) if tenant else (new, old)
        op.drop_index(drop[0], table_name=rec)
        op.create_index(create[0], rec, create[1], unique=True)


def _fk_columns(tenant: bool) -> tuple[list[str], list[str]]:
    return (["type_id", COLUMN], ["id", COLUMN]) if tenant else (["type_id"], ["id"])


def _swap_fks_pg(sets: Sequence[TableSet], *, tenant: bool) -> None:
    local, remote = _fk_columns(tenant)
    for tables in sets:
        rec, name = tables.record.__tablename__, _fk_name(tables)
        op.drop_constraint(name, rec, type_="foreignkey")
        op.create_foreign_key(name, rec, TYPE_TABLE, local, remote, ondelete="RESTRICT")


def _rebuild_sqlite(sets: Sequence[TableSet], *, tenant: bool) -> None:
    """Every constraint change on SQLite, one table rebuild per owned table."""
    records = {tables.record.__tablename__: tables for tables in sets}
    local, remote = _fk_columns(tenant)
    for table in _owned(sets):
        with op.batch_alter_table(table, recreate="always") as batch:
            if tenant:
                batch.alter_column(
                    COLUMN,
                    server_default=None,
                    existing_type=sa.String(50),
                    existing_nullable=False,
                )
            if table == TYPE_TABLE:
                if tenant:
                    batch.create_unique_constraint(TYPE_ID_TENANT, ["id", COLUMN])
                else:
                    batch.drop_constraint(TYPE_ID_TENANT, type_="unique")
            if table in records:
                name = _fk_name(records[table])
                batch.drop_constraint(name, type_="foreignkey")
                batch.create_foreign_key(name, TYPE_TABLE, local, remote, ondelete="RESTRICT")
            if not tenant:
                batch.drop_column(COLUMN)


def _descending_indexes(sets: Sequence[TableSet]) -> Iterator[sa.Index]:
    for tables in sets:
        table = tables.record.__table__
        wanted = set(descending_index_names(table.name))
        yield from (index for index in table.indexes if index.name in wanted)


def _repair_sqlite(bind, sets: Sequence[TableSet]) -> None:
    """Re-issue the ``DESC`` indexes the batch rebuild flattened, then ``ANALYZE``."""
    for index in _descending_indexes(sets):
        op.drop_index(index.name, table_name=index.table.name)
        index.create(bind)
    for table in _owned(sets):
        try:
            bind.execute(sa.text(f"ANALYZE {table}"))
        except sa.exc.OperationalError:  # pragma: no cover - lock contention only
            return


def upgrade() -> None:
    sets = _present_sets()
    bind = op.get_bind()
    for table in _owned(sets):
        op.add_column(table, _column(server_default=DEFAULT))
        op.create_index(f"ix_{table}_{COLUMN}", table, [COLUMN])
    _swap_natural_keys(sets, tenant=True)
    if bind.dialect.name != "sqlite":
        op.create_unique_constraint(TYPE_ID_TENANT, TYPE_TABLE, ["id", COLUMN])
        _swap_fks_pg(sets, tenant=True)
        for table in _owned(sets):
            op.alter_column(
                table,
                COLUMN,
                server_default=None,
                existing_type=sa.String(50),
                existing_nullable=False,
            )
        return
    _rebuild_sqlite(sets, tenant=True)
    _repair_sqlite(bind, sets)


def _shared_natural_keys(bind, sets: Sequence[TableSet]) -> list[str]:
    """Every type key, and every record uuid within a set, that more than one
    tenant holds — the rows the restored global uniques cannot take."""
    probes = [(TYPE_TABLE, "key")] + [(t.record.__tablename__, "uuid") for t in sets]
    found = []
    for table, column in probes:
        rows = bind.execute(
            sa.text(
                f"SELECT {column}, count(DISTINCT {COLUMN}) FROM {table} "
                f"GROUP BY {column} HAVING count(*) > 1 ORDER BY {column} LIMIT 20"
            )
        ).all()
        found += [f"{table}.{column}={value!r} ({n} tenants)" for value, n in rows]
    return found


def _refuse_if_shared(bind, sets: Sequence[TableSet]) -> None:
    """Refuse *before any DDL*: on SQLite the DDL is not transactional, so a
    unique that fails half way would leave the schema half downgraded while
    ``alembic_version`` still says head (review M1). Offline, nothing to read."""
    if op.get_context().as_sql:
        return
    shared = _shared_natural_keys(bind, sets)
    if shared:
        raise RuntimeError(
            "records: refusing to downgrade 4ecb931245dd — the global uniques it restores "
            "cannot hold while tenants share these (first 20 per table): "
            + "; ".join(shared)
            + ". Rename or delete the duplicates in all but one tenant, then retry. "
            "Nothing was changed."
        )


def downgrade() -> None:
    sets = _present_sets()
    bind = op.get_bind()
    _refuse_if_shared(bind, sets)
    if bind.dialect.name != "sqlite":
        _swap_fks_pg(sets, tenant=False)
        op.drop_constraint(TYPE_ID_TENANT, TYPE_TABLE, type_="unique")
    _swap_natural_keys(sets, tenant=False)
    for table in _owned(sets):
        op.drop_index(f"ix_{table}_{COLUMN}", table_name=table)
    if bind.dialect.name != "sqlite":
        for table in _owned(sets):
            op.drop_column(table, COLUMN)
        return
    _rebuild_sqlite(sets, tenant=False)
    _repair_sqlite(bind, sets)
