"""records type collection: which table set a type's documents live in

Revision ID: 5e2a32dccc22
Revises: 26bfe5e5f063
Create Date: 2026-09-20 11:25:25.568877

Autogenerated and left as generated. Phase 5 §6.2: ``records_type.collection``
names the collection whose tables hold this type's records, or is ``NULL`` for
the shared ones.

**Nullable, with no backfill, deliberately.** ``NULL`` is not a placeholder
here — it is the value the global table set has, so every existing row is
already correct the moment the column exists and a backfill would have nothing
to write. That is what makes the column additive, and what makes the whole
feature inert on a host that declares no collection (§6.5): this revision is
the only schema change such a host ever applies for collections, and after it
``alembic check`` is clean.

The tables a collection needs are **not** here. They exist only for a host that
calls ``declare_collection()``, so they are autogenerated per host against that
host's own declarations — in this repo, the ``events`` collection of the demo
host in the revision above this one.

Downgrading drops the column, which is safe exactly when no type is using it:
a type with a non-NULL ``collection`` would come back pointing at the global
tables while its records sat in a collection's, so downgrade past this only
after moving or deleting those types.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5e2a32dccc22'
down_revision: str | None = '26bfe5e5f063'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records_type', sa.Column('collection', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records_type', 'collection')
    # ### end Alembic commands ###
