"""add news categories and tags

Revision ID: 7fa1b9a883ff
Revises: 52d927feccb3
Create Date: 2026-08-19 13:55:23.834676
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7fa1b9a883ff'
down_revision: str | None = '52d927feccb3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_categories',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_categories'))
    )
    op.create_index(op.f('ix_news_categories_name'), 'news_categories', ['name'], unique=True)
    op.create_index(op.f('ix_news_categories_position'), 'news_categories', ['position'], unique=False)
    op.create_index(op.f('ix_news_categories_slug'), 'news_categories', ['slug'], unique=True)
    op.create_table('news_tags',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_tags'))
    )
    op.create_index(op.f('ix_news_tags_name'), 'news_tags', ['name'], unique=True)
    op.create_index(op.f('ix_news_tags_slug'), 'news_tags', ['slug'], unique=True)
    op.create_table('news_article_tags',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], name=op.f('fk_news_article_tags_article_id_news_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['news_tags.id'], name=op.f('fk_news_article_tags_tag_id_news_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id', name=op.f('pk_news_article_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_article_tags')
    op.drop_index(op.f('ix_news_tags_slug'), table_name='news_tags')
    op.drop_index(op.f('ix_news_tags_name'), table_name='news_tags')
    op.drop_table('news_tags')
    op.drop_index(op.f('ix_news_categories_slug'), table_name='news_categories')
    op.drop_index(op.f('ix_news_categories_position'), table_name='news_categories')
    op.drop_index(op.f('ix_news_categories_name'), table_name='news_categories')
    op.drop_table('news_categories')
    # ### end Alembic commands ###
