"""add news article scheduling

Two nullable instants, both indexed because the scheduler queries them every
tick and an unindexed scan of the whole archive every thirty seconds is the
kind of cost that only shows up once the archive is large.

Deliberately separate from ``published_at``, which is the article's *display*
date and documented as independent of status — back-dating a draft is ordinary
editorial work, and publishing on that column would put every back-dated draft
live at the next tick.

Revision ID: 8fd18ebe15e4
Revises: 7a1a2e92f6df
Create Date: 2026-08-26 17:49:49.355040
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8fd18ebe15e4'
down_revision: str | None = '7a1a2e92f6df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('news_articles', sa.Column('unpublish_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_news_articles_publish_at'), 'news_articles', ['publish_at'], unique=False)
    op.create_index(op.f('ix_news_articles_unpublish_at'), 'news_articles', ['unpublish_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_articles_unpublish_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_publish_at'), table_name='news_articles')
    op.drop_column('news_articles', 'unpublish_at')
    op.drop_column('news_articles', 'publish_at')
    # ### end Alembic commands ###
