"""add page parent and template flag

Revision ID: af06f6ea093e
Revises: 7fa1b9a883ff
Create Date: 2026-08-19 15:01:47.845087

Hand-adjusted from the autogenerated version in two places, both of which would
have failed on a database that already holds pages:

* ``is_template`` is NOT NULL, so it needs a ``server_default`` — without one
  the ALTER has no value to write into existing rows and the migration aborts.
  The default is dropped again afterwards so the application, not the database,
  owns the column's default from here on.
* Autogenerate emitted the column but not its self-referential foreign key.
  SQLite cannot add a constraint with a bare ALTER, so both columns go in inside
  ``batch_alter_table``, which recreates the table there and passes straight
  through to ALTER on Postgres.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af06f6ea093e"
down_revision: str | None = "7fa1b9a883ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLE = "pagebuilder_pages"


def upgrade() -> None:
    with op.batch_alter_table(_TABLE) as batch:
        batch.add_column(sa.Column("parent_id", sa.Integer(), nullable=True))
        batch.add_column(
            sa.Column(
                "is_template",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch.create_foreign_key(
            op.f("fk_pagebuilder_pages_parent_id_pagebuilder_pages"),
            _TABLE,
            ["parent_id"],
            ["id"],
            ondelete="SET NULL",
        )

    op.create_index(
        op.f("ix_pagebuilder_pages_is_template"), _TABLE, ["is_template"], unique=False
    )
    op.create_index(
        op.f("ix_pagebuilder_pages_parent_id"), _TABLE, ["parent_id"], unique=False
    )

    # Existing rows now carry `false`; leaving the server default in place would
    # let a future insert bypass the model's own default silently.
    with op.batch_alter_table(_TABLE) as batch:
        batch.alter_column("is_template", server_default=None)


def downgrade() -> None:
    op.drop_index(op.f("ix_pagebuilder_pages_parent_id"), table_name=_TABLE)
    op.drop_index(op.f("ix_pagebuilder_pages_is_template"), table_name=_TABLE)
    with op.batch_alter_table(_TABLE) as batch:
        batch.drop_constraint(
            op.f("fk_pagebuilder_pages_parent_id_pagebuilder_pages"),
            type_="foreignkey",
        )
        batch.drop_column("is_template")
        batch.drop_column("parent_id")
