"""add pagebuilder content snapshots

Revision ID: b98d8185ecef
Revises: 6504b2249610
Create Date: 2026-08-28 20:54:53.823825
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b98d8185ecef'
down_revision: str | None = '6504b2249610'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagebuilder_snapshots',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'UPLOAD', 'PRE_RESTORE', name='pagebuilder_snapshot_source'), nullable=False),
    sa.Column('format_version', sa.Integer(), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagebuilder_snapshots'))
    )
    op.create_index(op.f('ix_pagebuilder_snapshots_source'), 'pagebuilder_snapshots', ['source'], unique=False)
    op.create_table('pagebuilder_pending_imports',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='pagebuilder_import_status'), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['pagebuilder_snapshots.id'], name=op.f('fk_pagebuilder_pending_imports_snapshot_id_pagebuilder_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagebuilder_pending_imports'))
    )
    op.create_index(op.f('ix_pagebuilder_pending_imports_snapshot_id'), 'pagebuilder_pending_imports', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_pagebuilder_pending_imports_status'), 'pagebuilder_pending_imports', ['status'], unique=False)
    # Backs the "at most one import is pending at a time" invariant at the
    # database level — the service layer's check-then-insert alone cannot
    # close the race between two concurrent restore requests.
    op.create_index(
        'uq_pagebuilder_pending_imports_one_pending',
        'pagebuilder_pending_imports',
        ['status'],
        unique=True,
        sqlite_where=sa.text("status = 'PENDING'"),
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table('pagebuilder_snapshot_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bundle_name', sa.String(length=300), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('folder', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['pagebuilder_snapshots.id'], name=op.f('fk_pagebuilder_snapshot_media_snapshot_id_pagebuilder_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagebuilder_snapshot_media'))
    )
    op.create_index(op.f('ix_pagebuilder_snapshot_media_sha256'), 'pagebuilder_snapshot_media', ['sha256'], unique=False)
    op.create_index(op.f('ix_pagebuilder_snapshot_media_snapshot_id'), 'pagebuilder_snapshot_media', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_pagebuilder_pending_imports_one_pending', table_name='pagebuilder_pending_imports')
    op.drop_index(op.f('ix_pagebuilder_snapshot_media_snapshot_id'), table_name='pagebuilder_snapshot_media')
    op.drop_index(op.f('ix_pagebuilder_snapshot_media_sha256'), table_name='pagebuilder_snapshot_media')
    op.drop_table('pagebuilder_snapshot_media')
    op.drop_index(op.f('ix_pagebuilder_pending_imports_status'), table_name='pagebuilder_pending_imports')
    op.drop_index(op.f('ix_pagebuilder_pending_imports_snapshot_id'), table_name='pagebuilder_pending_imports')
    op.drop_table('pagebuilder_pending_imports')
    op.drop_index(op.f('ix_pagebuilder_snapshots_source'), table_name='pagebuilder_snapshots')
    op.drop_table('pagebuilder_snapshots')
    # ### end Alembic commands ###
