"""records: descending indexes for the nullable sortable columns

Revision ID: c4a17b9de0f2
Revises: fe3ea2dfe0fb
Create Date: 2026-09-20 15:20:00.000000

F5 gave ``position``, ``published_at``, ``updated_at``, ``created_at``,
``display_title`` and ``slug`` a ``(type_id, <column>, id)`` index each, and
``index/_sorting`` drops ``NULLS LAST`` only where the mapper says the column is
``NOT NULL``. ``published_at``, ``updated_at`` and ``slug`` are not, so a
*descending* page on one of them asks for
``ORDER BY col DESC NULLS LAST, id DESC`` — and on **Postgres** that is neither
direction of an ascending btree: reading ``ASC NULLS LAST`` backwards yields
``DESC NULLS FIRST``. The planner therefore ignored the index and sorted the
whole type to return 25 rows, on ``-updated_at`` (the second term of the admin
list's default ordering) and on ``-published_at`` (what a content listing sorts
by). See ``modules/records/docs/performance.md`` § S2.

This adds the second index each of those three needs, declared in the order the
query asks for. On SQLite it is ``(type_id, col DESC, id DESC)`` — SQLite has no
``NULLS`` clause in ``CREATE INDEX`` and needs none, because it sorts ``NULL``
smallest and ``DESC`` already puts them last.

**Derived from the factory rather than spelled out**, for the reason
``fe3ea2dfe0fb`` gives at length: index names are schema-global on Postgres, so
each table set's copies are named after *its* table, and which sets exist is the
host's decision (Phase 5 §6.1). The ``Index`` objects are the model's own —
expression indexes are not expressible through ``op.create_index`` — so what is
created here is exactly what ``create_all`` would create, and cannot drift from
it.

**But which sets to create them on comes from the database, not from the
declarations**, by exactly the rule ``fe3ea2dfe0fb`` states and for exactly the
same reason: ``table_sets()`` answers what this host declares *today*, while a
revision may only touch tables that exist at *its* point in the chain. A
collection declared after this revision was written has its tables created
above it, by its own autogenerated migration, already carrying these three
indexes — so on a fresh database this revision must skip it rather than
``CREATE INDEX`` onto a table that is not there yet. See
:func:`_present_sets`.

**And then it runs ``ANALYZE``, on SQLite, and that is not optional.** A new
index with no ``sqlite_stat1`` row is not "unknown" to SQLite's planner — it is
*assumed to be very selective*, which is how a 20,000-row index nobody has
measured beats the one that has been. Creating these three and stopping there
made every unsorted list page and every ``ORDER BY position`` page drive from
``(type_id, updated_at DESC, id DESC)`` and sort the result into a temp B-tree:
a list page went from 1.1 ms to 26.5 ms, and page 200 from 2.4 ms to 45.3 ms,
on a database whose *other* indexes were analysed. One ``ANALYZE`` per document
table puts every plan back. It is the same claim
:mod:`sm_records.index._analyze` already makes for the end of a reindex and the
end of a seeding run — a moment that has just rewritten the module's own
indexes and is out of any request by construction — made once more for the
moment that adds one.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sm_records.models import TableSet, table_sets
from sm_records.models._record_args import descending_index_names

# revision identifiers, used by Alembic.
revision: str = "c4a17b9de0f2"
down_revision: str | None = "fe3ea2dfe0fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _present_sets() -> tuple[TableSet, ...]:
    """The declared table sets whose document table exists **in this database**.

    The rule ``fe3ea2dfe0fb._present_sets`` sets out, applied a second time:
    act on the tables that are there at this point in the chain, not on the
    collections the host happens to declare now. A set declared later is
    created above this revision by its own autogenerated migration, which
    writes these indexes from the current model; a set declared now but not yet
    created here would be a ``CREATE INDEX`` on a missing table. The global set
    is always present.

    Offline (``--sql``) there is no database to ask, so every declared set is
    emitted — the script is generated for the host whose declarations are
    loaded.
    """
    if op.get_context().as_sql:
        return table_sets()
    present = set(sa.inspect(op.get_bind()).get_table_names())
    return tuple(tables for tables in table_sets() if tables.record.__tablename__ in present)


def _indexes():
    """Every present table set's descending indexes, as the model declares them."""
    for tables in _present_sets():
        table = tables.record.__table__
        wanted = set(descending_index_names(table.name))
        for index in sorted(table.indexes, key=lambda item: item.name or ""):
            if index.name in wanted:
                yield index


def _analyze(bind) -> None:
    """Refresh SQLite's statistics for the tables whose indexes just changed.

    SQLite only: Postgres has autovacuum, and the study found its plans did not
    depend on a manual ``ANALYZE`` either way. Best effort — a revision that
    created its indexes must not fail because the statistics pass lost the
    write lock, which is the trade ``index/_analyze`` already makes.
    """
    if bind.dialect.name != "sqlite":
        return
    for tables in _present_sets():
        try:
            bind.execute(sa.text(f"ANALYZE {tables.record.__tablename__}"))
        except sa.exc.OperationalError:  # pragma: no cover - lock contention only
            return


def upgrade() -> None:
    bind = op.get_bind()
    for index in _indexes():
        index.create(bind)
    _analyze(bind)


def downgrade() -> None:
    bind = op.get_bind()
    for index in _indexes():
        index.drop(bind)
    # The statistics rows for the dropped indexes go with them; re-running it
    # is what leaves the database in the state the previous revision's readers
    # were measured in.
    _analyze(bind)
