"""add records

Revision ID: e23090832709
Revises: b1f4a72c9d30
Create Date: 2026-09-19 13:59:29.420033
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e23090832709'
down_revision: str | None = 'b1f4a72c9d30'
branch_labels: str | Sequence[str] | None = ("records",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records_type',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('label_plural', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('display_field', sa.String(length=64), nullable=True),
    sa.Column('slug_field', sa.String(length=64), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('allowed_roles', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reindex_pending', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_type'))
    )
    op.create_index(op.f('ix_records_type_key'), 'records_type', ['key'], unique=True)
    op.create_table('records_record',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='records_record_status'), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('display_title', sa.String(length=300), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['records_type.id'], name=op.f('fk_records_record_type_id_records_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_record'))
    )
    op.create_index(op.f('ix_records_record_published_at'), 'records_record', ['published_at'], unique=False)
    op.create_index(op.f('ix_records_record_status'), 'records_record', ['status'], unique=False)
    op.create_index(op.f('ix_records_record_type_id'), 'records_record', ['type_id'], unique=False)
    op.create_index('ix_records_record_type_slug', 'records_record', ['type_id', 'slug'], unique=True, postgresql_where=sa.text('slug IS NOT NULL'), sqlite_where=sa.text('slug IS NOT NULL'))
    op.create_index('ix_records_record_type_status_position', 'records_record', ['type_id', 'status', 'position'], unique=False)
    op.create_index(op.f('ix_records_record_uuid'), 'records_record', ['uuid'], unique=True)
    op.create_table('records_type_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('display_field', sa.String(length=64), nullable=True),
    sa.Column('slug_field', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['records_type.id'], name=op.f('fk_records_type_revision_type_id_records_type'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_type_revision'))
    )
    op.create_index('ix_records_type_revision_type_version', 'records_type_revision', ['type_id', 'version'], unique=False)
    op.create_table('records_index_bool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records_record.id'], name=op.f('fk_records_index_bool_record_id_records_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_index_bool'))
    )
    op.create_index('ix_records_index_bool_lookup', 'records_index_bool', ['type_id', 'field_key', 'value'], unique=False)
    op.create_index('ix_records_index_bool_record', 'records_index_bool', ['record_id'], unique=False)
    op.create_table('records_index_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records_record.id'], name=op.f('fk_records_index_date_record_id_records_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_index_date'))
    )
    op.create_index('ix_records_index_date_lookup', 'records_index_date', ['type_id', 'field_key', 'value'], unique=False)
    op.create_index('ix_records_index_date_record', 'records_index_date', ['record_id'], unique=False)
    op.create_table('records_index_datetime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records_record.id'], name=op.f('fk_records_index_datetime_record_id_records_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_index_datetime'))
    )
    op.create_index('ix_records_index_datetime_lookup', 'records_index_datetime', ['type_id', 'field_key', 'value'], unique=False)
    op.create_index('ix_records_index_datetime_record', 'records_index_datetime', ['record_id'], unique=False)
    op.create_table('records_index_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=19, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records_record.id'], name=op.f('fk_records_index_number_record_id_records_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_index_number'))
    )
    op.create_index('ix_records_index_number_lookup', 'records_index_number', ['type_id', 'field_key', 'value'], unique=False)
    op.create_index('ix_records_index_number_record', 'records_index_number', ['record_id'], unique=False)
    op.create_table('records_index_ref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('target_uuid', sa.String(length=32), nullable=False),
    sa.Column('target_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records_record.id'], name=op.f('fk_records_index_ref_record_id_records_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_index_ref'))
    )
    op.create_index('ix_records_index_ref_lookup', 'records_index_ref', ['type_id', 'field_key', 'target_uuid'], unique=False)
    op.create_index('ix_records_index_ref_record', 'records_index_ref', ['record_id'], unique=False)
    op.create_index('ix_records_index_ref_target', 'records_index_ref', ['target_uuid'], unique=False)
    op.create_table('records_index_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('value_full', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records_record.id'], name=op.f('fk_records_index_text_record_id_records_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_index_text'))
    )
    op.create_index('ix_records_index_text_lookup', 'records_index_text', ['type_id', 'field_key', 'value'], unique=False)
    op.create_index('ix_records_index_text_record', 'records_index_text', ['record_id'], unique=False)
    op.create_table('records_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('display_title', sa.String(length=300), nullable=False),
    sa.Column('event', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'RESTORE', name='records_revision_event'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records_record.id'], name=op.f('fk_records_revision_record_id_records_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records_revision'))
    )
    op.create_index('ix_records_revision_record_id', 'records_revision', ['record_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_records_revision_record_id', table_name='records_revision')
    op.drop_table('records_revision')
    op.drop_index('ix_records_index_text_record', table_name='records_index_text')
    op.drop_index('ix_records_index_text_lookup', table_name='records_index_text')
    op.drop_table('records_index_text')
    op.drop_index('ix_records_index_ref_target', table_name='records_index_ref')
    op.drop_index('ix_records_index_ref_record', table_name='records_index_ref')
    op.drop_index('ix_records_index_ref_lookup', table_name='records_index_ref')
    op.drop_table('records_index_ref')
    op.drop_index('ix_records_index_number_record', table_name='records_index_number')
    op.drop_index('ix_records_index_number_lookup', table_name='records_index_number')
    op.drop_table('records_index_number')
    op.drop_index('ix_records_index_datetime_record', table_name='records_index_datetime')
    op.drop_index('ix_records_index_datetime_lookup', table_name='records_index_datetime')
    op.drop_table('records_index_datetime')
    op.drop_index('ix_records_index_date_record', table_name='records_index_date')
    op.drop_index('ix_records_index_date_lookup', table_name='records_index_date')
    op.drop_table('records_index_date')
    op.drop_index('ix_records_index_bool_record', table_name='records_index_bool')
    op.drop_index('ix_records_index_bool_lookup', table_name='records_index_bool')
    op.drop_table('records_index_bool')
    op.drop_index('ix_records_type_revision_type_version', table_name='records_type_revision')
    op.drop_table('records_type_revision')
    op.drop_index(op.f('ix_records_record_uuid'), table_name='records_record')
    op.drop_index('ix_records_record_type_status_position', table_name='records_record')
    op.drop_index('ix_records_record_type_slug', table_name='records_record', postgresql_where=sa.text('slug IS NOT NULL'), sqlite_where=sa.text('slug IS NOT NULL'))
    op.drop_index(op.f('ix_records_record_type_id'), table_name='records_record')
    op.drop_index(op.f('ix_records_record_status'), table_name='records_record')
    op.drop_index(op.f('ix_records_record_published_at'), table_name='records_record')
    op.drop_table('records_record')
    op.drop_index(op.f('ix_records_type_key'), table_name='records_type')
    op.drop_table('records_type')
    # ### end Alembic commands ###
