"""records sort and lookup indexes

Revision ID: fccc111ff2e9
Revises: e23090832709
Create Date: 2026-09-20 08:16:39.409416
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'fccc111ff2e9'
down_revision: str | None = 'e23090832709'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_records_record_type_created_id', 'records_record', ['type_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_records_record_type_position_id', 'records_record', ['type_id', 'position', 'id'], unique=False)
    op.create_index('ix_records_record_type_published_id', 'records_record', ['type_id', 'published_at', 'id'], unique=False)
    op.create_index('ix_records_record_type_slug_id', 'records_record', ['type_id', 'slug', 'id'], unique=False)
    op.create_index('ix_records_record_type_title_id', 'records_record', ['type_id', 'display_title', 'id'], unique=False)
    op.create_index('ix_records_record_type_updated_id', 'records_record', ['type_id', 'updated_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_records_record_type_updated_id', table_name='records_record')
    op.drop_index('ix_records_record_type_title_id', table_name='records_record')
    op.drop_index('ix_records_record_type_slug_id', table_name='records_record')
    op.drop_index('ix_records_record_type_published_id', table_name='records_record')
    op.drop_index('ix_records_record_type_position_id', table_name='records_record')
    op.drop_index('ix_records_record_type_created_id', table_name='records_record')
    # ### end Alembic commands ###
