"""Enforce a maximum line count per source file.

Counts physical lines (``len(text.splitlines())``) so a trailing newline
does not change the total. Exits 1 if any covered file exceeds ``--max``
(default 300). Exempt paths matching ``--exempt`` globs are skipped.

By default scans the git working tree — tracked files plus untracked files
that aren't gitignored — so a brand-new oversized file fails the check
before it's committed (#204). ``--no-git`` walks the filesystem instead
(does not honour ``.gitignore``).

Usage:
    uv run python scripts/check_file_size.py
    uv run python scripts/check_file_size.py --max 200
    uv run python scripts/check_file_size.py --root some/subdir --no-git
"""

from __future__ import annotations

import argparse
import fnmatch
import subprocess
import sys
from collections.abc import Iterable, Sequence
from pathlib import Path

DEFAULT_MAX_LINES = 300
COVERED_SUFFIXES = {".py", ".ts", ".tsx"}
# The framework repo also exempts packages/ui and packages/i18n; neither
# exists here. No module source is exempt — that's the point of adopting
# this check from day one.
DEFAULT_EXEMPT_GLOBS: tuple[str, ...] = (
    # Alembic migrations are autogenerated from module metadata; an initial
    # migration covering every installed module's tables routinely exceeds
    # the cap and there's nothing meaningful to split out.
    "host/migrations/versions/**",
)


def count_lines(path: Path) -> int:
    """Return the number of physical lines in ``path``, or 0 if unreadable."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return 0
    return len(text.splitlines())


def is_covered(path: Path) -> bool:
    """Return True when the file's suffix is in scope."""
    return path.suffix in COVERED_SUFFIXES


def is_exempt(path: Path, exempt_globs: Iterable[str]) -> bool:
    """Return True when ``path`` matches any exempt glob."""
    posix = path.as_posix()
    return any(fnmatch.fnmatch(posix, pattern) for pattern in exempt_globs)


def find_violations(
    paths: Iterable[Path],
    *,
    max_lines: int,
    exemptions: Iterable[str],
    root: Path | None = None,
) -> list[tuple[Path, int]]:
    """Return (path, line_count) pairs over ``max_lines``, largest first.

    When ``root`` is given, exempt globs are matched against the path
    relative to ``root`` (so patterns like ``packages/ui/**`` work even
    when ``paths`` are absolute).
    """
    exempt_tuple = tuple(exemptions)
    violations: list[tuple[Path, int]] = []
    for path in paths:
        if not is_covered(path):
            continue
        match_target = _relative_for_match(path, root)
        if is_exempt(match_target, exempt_tuple):
            continue
        lines = count_lines(path)
        if lines > max_lines:
            violations.append((path, lines))
    violations.sort(key=lambda v: v[1], reverse=True)
    return violations


def _relative_for_match(path: Path, root: Path | None) -> Path:
    if root is None:
        return path
    try:
        return path.relative_to(root)
    except ValueError:
        return path


def _list_git_files(root: Path) -> list[Path]:
    """List tracked + untracked-but-not-ignored files via git.

    ``--cached`` covers tracked files and ``--others --exclude-standard``
    adds untracked files that aren't gitignored, so an oversized file is
    caught the moment it's written — not only after it's committed (#204).
    Gitignored paths (``.venv``, ``node_modules``, build output) stay out
    of scope, which a bare filesystem walk would not respect.
    """
    result = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    )
    return [root / line for line in result.stdout.splitlines() if line]


def _walk_filesystem(root: Path) -> list[Path]:
    return [p for p in root.rglob("*") if p.is_file()]


def _collect_candidates(root: Path, use_git: bool) -> list[Path]:
    return _list_git_files(root) if use_git else _walk_filesystem(root)


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    description = (__doc__ or "Enforce a maximum line count per source file.").splitlines()[0]
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument(
        "--max",
        type=int,
        default=DEFAULT_MAX_LINES,
        help=f"max allowed lines per file (default: {DEFAULT_MAX_LINES})",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="repo root to scan (default: cwd)",
    )
    parser.add_argument(
        "--exempt",
        action="append",
        default=None,
        help="additional exempt glob (repeatable); replaces defaults if given",
    )
    parser.add_argument(
        "--no-git",
        action="store_true",
        help="walk the filesystem instead of using git ls-files",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    exemptions: tuple[str, ...] = tuple(args.exempt) if args.exempt else DEFAULT_EXEMPT_GLOBS
    candidates = _collect_candidates(args.root, use_git=not args.no_git)
    violations = find_violations(
        candidates,
        max_lines=args.max,
        exemptions=exemptions,
        root=args.root,
    )
    if not violations:
        print(f"OK: no files exceed {args.max} lines.")
        return 0
    print(f"FAIL: {len(violations)} file(s) exceed {args.max} lines:")
    width = max(len(str(v[1])) for v in violations)
    for path, lines in violations:
        rel = path.relative_to(args.root) if path.is_absolute() else path
        print(f"  {lines:>{width}}  {rel.as_posix()}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
